name: Metrics
on:
  # Osvježava se svaka 24 sata
  schedule: [{cron: "0 0 * * *"}]
  # Dozvoljava ručno pokretanje
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Osnovne postavke
          user: amer-5
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Europe/Sarajevo
          
          # Jezici (Languages)
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          
          # Aktiviraj LeetCode ako želiš (opcionalno)
          # plugin_leetcode: yes
          # plugin_leetcode_user: amer-5
          # plugin_leetcode_sections: solved, skills, recent
